import wsRouter from './ws/ws.router.js';
import smsRouter from './sms/sms.router.js';
import formRouter from './form/form.router.js';
import likeRouter from './like/like.router.js';
import userRouter from './user/user.router.js';
import cityRouter from './city/city.router.js';
import pageRouter from './page/page.router.js';
import authRouter from './auth/auth.router.js';
import externalAuthRouter from './auth/external-auth.router.js';
import iikoRouter from './iiko/iiko.router.js';
import fileRouter from './file/file.router.js';
import orderRouter from './order/order.router.js';
import cladrRouter from './cladr/cladr.router.js';
import slideRouter from './slide/slide.router.js';
import storyRouter from './story/story.router.js';
import promoRouter from './promo/promo.router.js';
import settingRouter from './setting/setting.router.js';
import catalogRouter from './catalog/catalog.router.js';
import addressRouter from './address/address.router.js';
import paymentRouter from './payment/payment.router.js';
import storageRouter from './storage/storage.router.js';
import telegramRouter from './telegram/telegram.router.js';
import mapRouter from './map/map.router.js';
import mapAdminRouter from './map/admin.router.js';
import iikoAdapterRouter from './iiko-adapter/iiko-adapter.router.js';
import notificationRouter from './notification/notification.router.js';
import terminalsRouter from './terminals/terminals.router.js';
import remarkedRouter from './remarked/remarked.router.js';
import yandexFeedRouter from './feeds/yandex/feed.router.js';

export const registerRouters = (fastify) => {
  fastify.register(wsRouter, { prefix: '/api/v1/ws' });
  fastify.register(smsRouter, { prefix: '/api/v1/sms' });
  fastify.register(userRouter, { prefix: '/api/v1/user' });
  fastify.register(likeRouter, { prefix: '/api/v1/like' });
  fastify.register(cityRouter, { prefix: '/api/v1/city' });
  fastify.register(pageRouter, { prefix: '/api/v1/page' });
  fastify.register(formRouter, { prefix: '/api/v1/form' });
  fastify.register(authRouter, { prefix: '/api/v1/auth' });
  fastify.register(externalAuthRouter, { prefix: '/api/v1/auth' });
  fastify.register(iikoRouter, { prefix: '/api/v1/iiko' });
  fastify.register(fileRouter, { prefix: '/api/v1/file' });
  fastify.register(cladrRouter, { prefix: '/api/v1/cladr' });
  fastify.register(orderRouter, { prefix: '/api/v1/order' });
  fastify.register(slideRouter, { prefix: '/api/v1/slide' });
  fastify.register(storyRouter, { prefix: '/api/v1/story' });
  fastify.register(promoRouter, { prefix: '/api/v1/promo' });
  fastify.register(catalogRouter, { prefix: '/api/v1/catalog' });
  fastify.register(settingRouter, { prefix: '/api/v1/setting' });
  fastify.register(addressRouter, { prefix: '/api/v1/address' });
  fastify.register(paymentRouter, { prefix: '/api/v1/payment' });
  fastify.register(storageRouter, { prefix: '/api/v1/storage' });
  fastify.register(telegramRouter, { prefix: '/api/v1/telegram' });
  fastify.register(mapRouter, { prefix: '/api/v1/map/zones' });
  fastify.register(mapAdminRouter, { prefix: '/api/v1/admin/zones' });
  fastify.register(terminalsRouter, { prefix: '/api/v1/terminals' });
  fastify.register(notificationRouter, { prefix: '/api/v1/notification' });
  fastify.register(remarkedRouter, { prefix: '/api/v1/remarked' });
  fastify.register(iikoAdapterRouter, { prefix: '/api/0' });
  fastify.register(yandexFeedRouter, { prefix: '/api/v1/feeds/yandex' });
};
